namespace SignaturPortal.Application.Authorization;

/// <summary>
/// Complete permission enum matching the legacy PermissionHelper.Permission enum.
/// Values correspond to PermissionId in the Permission database table.
/// Source of truth: C:\Dev\Dev3Org\AtlantaSignatur\Library\Security\PermissionHelper.cs
/// </summary>
public enum PortalPermission
{
    // General
    GeneralCreateEditServiceMessage = 100,
    GeneralCreateEditHelpPageAlternative = 110,

    // Ad Portal
    AdPortalAdminAccess = 1000,
    AdPortalViewOtherUsersActivities = 1001,
    AdPortalViewOtherUsersDraftActivities = 1002,
    AdPortalEditOtherUsersDraftActivities = 1003,
    AdPortalViewActivitiesFromUserGroupsUserNotMemberOf = 1004,
    AdPortalEditOwnDraftActivities = 1005,
    AdPortalAllowChangeStatusDraftActivities = 1006,
    AdPortalAlwaysAllowCreateActivity = 1007,
    AdPortalAccess = 1050,
    AdPortalPublishWebAd = 1100,
    AdPortalPublishJobnet = 1101,
    AdPortalPublishNaturejobs = 1102,
    AdPortalPublishLinkedIn = 1103,
    AdPortalAllowInsertExtraMedia = 1150,
    AdPortalWebAdAiAssistance = 1160,
    AdPortalAllowDeleteActivity = 1200,
    AdPortalEditWebAdTemplates = 1500,
    AdPortalMediaStatisticsAccess = 1600,
    AdPortalAllowImpersonate = 1700,
    AllowUserActiveInactive = 1900,
    AllowUserDeletePermanent = 1901,

    // Recruitment Portal
    RecruitmentPortalRecruitmentAccess = 2000,
    RecruitmentPortalRecruitmentStatisticsAccess = 2010,
    RecruitmentPortalQuestionnaireStatisticsAccess = 2011,
    RecruitmentPortalMediaStatisticsAccess = 2012,
    RecruitmentPortalCreateActivity = 2020,
    RecruitmentPortalDeleteActivity = 2021,
    RecruitmentPortalViewDeletedActivities = 2022,
    RecruitmentPortalEditDeletedActivities = 2023,
    RecruitmentPortalAllowCloseActivityWithNotFinishedCandidates = 2024,
    RecruitmentPortalViewActivitiesUserNotMemberOf = 2025,
    RecruitmentPortalEditActivitiesUserNotMemberOf = 2026,
    RecruitmentPortalCreateDraftActivities = 2027,
    RecruitmentPortalViewDraftActivities = 2028,
    RecruitmentPortalEditDraftActivities = 2029,
    RecruitmentPortalAllowExportActivityMembersInActivityList = 2030,
    RecruitmentPortalAllowSelectWorkAreasThatUserIsNotMemberOf = 2034,
    RecruitmentPortalViewActivitiesFromWorkAreaUserNotMemberOf = 2035,
    RecruitmentPortalEditActivitiesFromWorkAreaUserNotMemberOf = 2036,
    RecruitmentPortalRepublishWebAdAndJobnetAdFromOwnRecruitmentActivity = 2040,
    RecruitmentPortalViewCandidateDetails = 2050,
    RecruitmentPortalCandidateEvaluation = 2051,
    RecruitmentPortalViewCandidateNotes = 2052,
    RecruitmentPortalCreateCandidateNote = 2053,
    RecruitmentPortalCandidateNoteCanDeleteOtherUsersNote = 2054,
    RecruitmentPortalAllowViewCandidateEvalutionAndNotesWhenUserHasNotEvaluated = 2055,
    RecruitmentPortalViewCandidateOtherApplicationsInCandidateList = 2056,
    RecruitmentPortalEditCandidate = 2060,
    RecruitmentPortalViewDeletedCandidates = 2061,
    RecruitmentPortalEditDeletedCandidates = 2062,
    RecruitmentPortalCandidateAllowSetPossibleCandidate = 2063,
    RecruitmentPortalDownloadCandidateHiredFile = 2065,
    RecruitmentPortalCandidatesAllowMoveAnotherActivityNotResponsible = 2066,
    RecruitmentPortalPermanentDeleteCandidates = 2068,
    RecruitmentPortalRecruitmentResponsible = 2070,
    RecruitmentPortalAllowSearchCandidates = 2080,
    RecruitmentPortalAllowDeleteCandidatesFromSearchCandidates = 2082,
    RecruitmentPortalAllowExternalCandidateExport = 2085,
    RecruitmentPortalAllowSearchJobProfiles = 2090,
    RecruitmentPortalDeleteJobProfiles = 2092,
    RecruitmentPortalEditJobProfiles = 2094,
    RecruitmentPortalAllowSearchJobAgents = 2096,
    RecruitmentPortalDeleteJobAgents = 2097,
    RecruitmentPortalEditJobAgents = 2098,
    RecruitmentPortalViewActivityNotes = 2100,
    RecruitmentPortalCreateActivityNote = 2101,
    RecruitmentPortalActivityNoteCanDeleteOtherUsersNote = 2102,
    RecruitmentPortalViewJobBanksWhereUserNotResponsible = 2200,
    RecruitmentPortalCreateEditJobBanks = 2202,
    RecruitmentPortalEditJobBanksWhereUserNotResponsible = 2204,
    RecruitmentPortalViewJobBankCandidatesFromJobBanksUserNotMemberOf = 2206,
    RecruitmentPortalEditJobBankCandidate = 2208,
    RecruitmentPortalPermanentDeleteJobBankCandidates = 2209,
    RecruitmentPortalAllowCreateQuickHireFromJobBanksUserNotMemberOf = 2250,
    RecruitmentPortalAdminAccess = 2500,
    RecruitmentPortalViewMailTemplates = 2510,
    RecruitmentPortalCreateMailTemplates = 2511,
    RecruitmentPortalViewSmsTemplates = 2515,
    RecruitmentPortalCreateSmsTemplates = 2516,
    RecruitmentPortalViewApplicationTemplates = 2520,
    RecruitmentPortalCreateApplicationTemplates = 2521,
    RecruitmentPortalViewGrossApplicationTemplate = 2522,
    RecruitmentPortalEditGrossApplicationTemplate = 2523,
    RecruitmentPortalEditGrossApplicationTemplateFieldNameAndElementName = 2524,
    RecruitmentPortalViewLists = 2530,
    RecruitmentPortalCreateLists = 2531,
    RecruitmentPortalViewQuestionnaires = 2540,
    RecruitmentPortalCreateEditQuestionnaires = 2541,
    RecruitmentPortalViewUsers = 2550,
    RecruitmentPortalCreateUsers = 2551,
    RecruitmentPortalViewExternalUsers = 2555,
    RecruitmentPortalEditExternalUsers = 2556,
    RecruitmentPortalViewUserLog = 2560,
    RecruitmentPortalEditSsoUsers = 2570,

    // Onboarding Portal
    OnboardingPortalOnboardingAccess = 3000,
    OnBoardingPortalEditProcessesUserNotMemberOf = 3010,
    OnBoardingPortalDeleteProcess = 3011,
    OnBoardingPortalCreateEditProcesses = 3013,
    OnBoardingPortalAllowCreateEmployeeWhenCreateProcess = 3014,
    OnboardingPortalViewProcessesUserNotMemberOf = 3015,
    OnboardingPortalBoardingResponsible = 3017,
    OnboardingPortalAllowSelectWorkAreasThatUserIsNotMemberOf = 3020,
    OnboardingPortalViewProcessesFromWorkAreaUserNotMemberOf = 3021,
    OnboardingPortalEditProcessesFromWorkAreaUserNotMemberOf = 3022,
    OnboardingPortalAdminAccess = 3500,
    OnboardingPortalViewTemplates = 3510,
    OnboardingPortalCreateEditTemplates = 3511,
    OnboardingPortalEditTemplateWhereUserNotResponsible = 3512,
    OnboardingPortalViewGrossTemplates = 3515,
    OnboardingPortalCreateEditGrossTemplates = 3516,
    OnboardingPortalViewLetterTemplates = 3530,
    OnboardingPortalCreateEditLetterTemplates = 3531,
    OnboardingPortalViewQuestionnaires = 3540,
    OnboardingPortalCreateEditQuestionnaires = 3541,
    OnboardingPortalViewUsers = 3550,
    OnboardingPortalCreateEditUsers = 3551,
    OnboardingPortalViewUserLog = 3560,
    OnboardingPortalQuestionnaireStatisticsAccess = 3600,

    // Special / Cross-Portal
    AdPortalRecruitmentSpecialAdministratorActions = 9000,
    AdPortalCreateEditSignaturUsers = 9020,
    AdPortalCreateEditRoles = 9022,
    AdPortalEditActivityMediaStatistics = 9040,
    AdPortalUsersMergeAllow = 9050,
    AdPortalWebAdAiAssistanceAlways = 9060,
}
